/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 12-Mar-2018 12:32:42
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 12
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017b\extern\include\tmwtypes.h 
 */
const int BL = 12;
const real64_T B[12] = {
    0.04663621300746,  0.04897280050623,  0.06768560325823,  0.08483278114231,
    0.09799369794172,   0.1050899721054,   0.1050899721054,  0.09799369794172,
    0.08483278114231,  0.06768560325823,  0.04897280050623,  0.04663621300746
};
